name: notification_app
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.2.1
  go_router: ^14.1.4
  provider: ^6.1.5
  flutter_local_notifications: ^17.1.2
  device_preview: ^1.2.0
  flutter_svg: ^2.1.0
  flutter_launcher_icons: ^0.14.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/reminder.png"
  min_sdk_android: 21
  
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: Technor
      fonts:
        - asset: assets/fonts/OTF/Technor-Regular.otf
        - asset: assets/fonts/OTF/Technor-Bold.otf
          weight: 700
        - asset: assets/fonts/OTF/Technor-Light.otf
          weight: 300
        - asset: assets/fonts/OTF/Technor-Black.otf
          weight: 900
