// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAHjOZjgA7qE8xuAP2i5s0U_3ERXNXE_Tc',
    appId: '1:755416427977:android:75a80e321a7086ebd78c18',
    messagingSenderId: '755416427977',
    projectId: 'froggify',
    storageBucket: 'froggify.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDHpqD2c8zEweGucbOEVmR6kOjC9LSeIQA',
    appId: '1:755416427977:ios:9a5082a8c5e576a4d78c18',
    messagingSenderId: '755416427977',
    projectId: 'froggify',
    storageBucket: 'froggify.firebasestorage.app',
    androidClientId: '755416427977-9e85r4v297k7l14489v5i3m6vsp5ums4.apps.googleusercontent.com',
    iosClientId: '755416427977-63p1b8474vi5045an235r2dp01mcofg3.apps.googleusercontent.com',
    iosBundleId: 'com.example.notificationApp',
  );
}
